# general
alias ll='ls -lh'
alias la='ls -A'
alias sl='ls'
alias h='history'
alias rdp='rdesktop -a 16 -k en-us -u administrator'
alias grep='grep --color=always'
alias md='mkdir -p'

# rails
alias sc='script/console'
alias ss='script/server'
alias rr='rake routes'
alias rdbm='rake db:migrate'
alias rdbr='rake db:rollback'
alias rdbtp='rake db:test:prepare'

# git
alias ga='git add'
alias gst='git status'
alias gp='git push'
alias gpom='git push origin master'
alias gl='git pull'
alias glom='git pull origin master'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'
alias gd='git diff | $EDITOR'
alias gh='github'
